### ISSUE TITLE
"SELECT TOP 10/ 100/ N/ N without query" commands do not work

### ISSUE THREAD

**Issue by ddimkovikj** [jimmystelzer/azuredatastudio-select-top-n#1]
None of the following commands seem to work:
![image](https://user-images.githubusercontent.com/23528973/104009017-a5a0c880-51aa-11eb-90bb-70d5d254b7ee.png)
The only thing that works correctly is `SELECT TOP 1000`.

Expected result:
```
Command should open new window, display and execute the query.
```

Actual result:
```
Nothing happens.
```
System info:
```
OS: Windows 10 Enterprise build 18363
Azure Data Studio Select Top N: v0.0.4
Azure Data Studio: v1.25.1
```

**Comment by jimmystelzer** [comment]
@ddimkovikj I develop this extension under Linux and that is why I delayed to response this issue. I have made a new installation of the Azure Data Studio under Windows 10 Professional to check that and do not found any issue, as you can see in this video https://youtu.be/UwQgFHCMntg . 
Maybe we can make further investigations to found the related issue, if you can give more informations and run some tests.

For start can you give the information about the SQL Server version? So I can test in your version too.
So far I have tested this extension with SQL Server 2012 Enterprise and SQL Server 2019 Express.

Do you use another extension? Can you give the list so I can check if there is incompatibility? 

Microsoft offers a sample databases (AdventureWorks) to test purpose that maybe we can use to isolate this issue and check if this has relation with the database schema.
https://docs.microsoft.com/en-us/sql/samples/adventureworks-install-configure?view=sql-server-ver15&tabs=data-studio

Maybe this has relation if the user permission, can you test this with a more privileged user in the SQL Server or try to do a query to read the table schema (change **YorDatabaseNameHere** with you information):

`USE YorDatabaseNameHere; SELECT TOP 10 [COLUMN_NAME] FROM INFORMATION_SCHEMA.COLUMNS`

**Comment by jimmystelzer** [comment]
@ddimkovikj I think that I found something. I have create a database with a reserved word from SQL to test if works and that is fails. My test database name is UPDATE. Can you confirm if in your case the database or table is a reserved word from SQL?

If that is the case I will push a fix soon.
